'use strict';

const bcrypt = require('bcryptjs');
const {
  DESIGNATION,
  DEPARTMENT,
  EMPLOYEE_STATUS,
  USER_ROLE,
} = require('../constants');

module.exports = {
  async up(queryInterface, Sequelize) {
    const hashedPassword = await bcrypt.hash('123456', 10);

    await queryInterface.bulkInsert('users', [
      {
        name: 'John Doe',
        email: 'john.doe@gmail.com',
        password: hashedPassword,
        designation: DESIGNATION.SOFTWARE_ENGINEER,
        department: DEPARTMENT.ENGINEERING,
        dateOfBirth: '1992-03-15',
        profilePictureKey: null,
        employeeId: 'EMP-001',
        salary: 80000.0,
        joiningDate: '2021-06-01',
        phoneNumber: '9876543211',
        status: EMPLOYEE_STATUS.CURRENT_EMPLOYEE,
        role: USER_ROLE.EMPLOYEE,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Jane Smith',
        email: 'jane.smith@gmail.com',
        password: hashedPassword,
        designation: DESIGNATION.QA_ENGINEER,
        department: DEPARTMENT.QUALITY_ASSURANCE,
        dateOfBirth: '1988-07-22',
        profilePictureKey: null,
        employeeId: 'EMP-002',
        salary: 75000.0,
        joiningDate: '2019-02-10',
        phoneNumber: '9876543212',
        status: EMPLOYEE_STATUS.CURRENT_EMPLOYEE,
        role: USER_ROLE.EMPLOYEE,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Michael Brown',
        email: 'michael.brown@gmail.com',
        password: hashedPassword,
        designation: DESIGNATION.DEVOPS_ENGINEER,
        department: DEPARTMENT.ENGINEERING,
        dateOfBirth: '1990-11-05',
        profilePictureKey: null,
        employeeId: 'EMP-003',
        salary: 90000.0,
        joiningDate: '2020-09-15',
        phoneNumber: '9876543213',
        status: EMPLOYEE_STATUS.CURRENT_EMPLOYEE,
        role: USER_ROLE.EMPLOYEE,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Emily Davis',
        email: 'emily.davis@gmail.com',
        password: hashedPassword,
        designation: DESIGNATION.HR_SPECIALIST,
        department: DEPARTMENT.HUMAN_RESOURCES,
        dateOfBirth: '1985-12-30',
        profilePictureKey: null,
        employeeId: 'EMP-004',
        salary: 70000.0,
        joiningDate: '2018-03-01',
        phoneNumber: '9876543214',
        status: EMPLOYEE_STATUS.OLD_EMPLOYEE,
        role: USER_ROLE.EMPLOYEE,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'William Johnson',
        email: 'william.johnson@gmail.com',
        password: hashedPassword,
        designation: DESIGNATION.PRODUCT_MANAGER,
        department: DEPARTMENT.PRODUCT,
        dateOfBirth: '1987-08-18',
        profilePictureKey: null,
        employeeId: 'EMP-005',
        salary: 110000.0,
        joiningDate: '2017-05-12',
        phoneNumber: '9876543215',
        status: EMPLOYEE_STATUS.CURRENT_EMPLOYEE,
        role: USER_ROLE.EMPLOYEE,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Olivia Wilson',
        email: 'olivia.wilson@gmail.com',
        password: hashedPassword,
        designation: DESIGNATION.UI_UX_DESIGNER,
        department: DEPARTMENT.DESIGN,
        dateOfBirth: '1993-04-27',
        profilePictureKey: null,
        employeeId: 'EMP-006',
        salary: 85000.0,
        joiningDate: '2021-11-20',
        phoneNumber: '9876543216',
        status: EMPLOYEE_STATUS.CURRENT_EMPLOYEE,
        role: USER_ROLE.EMPLOYEE,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'David Martinez',
        email: 'david.martinez@gmail.com',
        password: hashedPassword,
        designation: DESIGNATION.DATA_ANALYST,
        department: DEPARTMENT.ANALYTICS,
        dateOfBirth: '1991-02-14',
        profilePictureKey: null,
        employeeId: 'EMP-007',
        salary: 78000.0,
        joiningDate: '2019-09-01',
        phoneNumber: '9876543217',
        status: EMPLOYEE_STATUS.OLD_EMPLOYEE,
        role: USER_ROLE.EMPLOYEE,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Sophia Anderson',
        email: 'sophia.anderson@gmail.com',
        password: hashedPassword,
        designation: DESIGNATION.MARKETING_EXECUTIVE,
        department: DEPARTMENT.MARKETING,
        dateOfBirth: '1990-06-10',
        profilePictureKey: null,
        employeeId: 'EMP-008',
        salary: 65000.0,
        joiningDate: '2020-01-05',
        phoneNumber: '9876543218',
        status: EMPLOYEE_STATUS.CURRENT_EMPLOYEE,
        role: USER_ROLE.EMPLOYEE,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'James Taylor',
        email: 'james.taylor@gmail.com',
        password: hashedPassword,
        designation: DESIGNATION.FINANCE_ANALYST,
        department: DEPARTMENT.FINANCE,
        dateOfBirth: '1989-09-23',
        profilePictureKey: null,
        employeeId: 'EMP-009',
        salary: 90000.0,
        joiningDate: '2018-07-15',
        phoneNumber: '9876543219',
        status: EMPLOYEE_STATUS.OLD_EMPLOYEE,
        role: USER_ROLE.EMPLOYEE,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Isabella Thomas',
        email: 'isabella.thomas@gmail.com',
        password: hashedPassword,
        designation: DESIGNATION.CONTENT_WRITER,
        department: DEPARTMENT.CONTENT,
        dateOfBirth: '1994-01-19',
        profilePictureKey: null,
        employeeId: 'EMP-010',
        salary: 60000.0,
        joiningDate: '2022-03-10',
        phoneNumber: '9876543220',
        status: EMPLOYEE_STATUS.CURRENT_EMPLOYEE,
        role: USER_ROLE.EMPLOYEE,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Benjamin White',
        email: 'benjamin.white@gmail.com',
        password: hashedPassword,
        designation: DESIGNATION.SUPPORT_ENGINEER,
        department: DEPARTMENT.SUPPORT,
        dateOfBirth: '1992-05-02',
        profilePictureKey: null,
        employeeId: 'EMP-011',
        salary: 70000.0,
        joiningDate: '2021-08-25',
        phoneNumber: '9876543221',
        status: EMPLOYEE_STATUS.CURRENT_EMPLOYEE,
        role: USER_ROLE.EMPLOYEE,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Mia Harris',
        email: 'mia.harris@gmail.com',
        password: hashedPassword,
        designation: DESIGNATION.HR_MANAGER,
        department: DEPARTMENT.HUMAN_RESOURCES,
        dateOfBirth: '1986-11-12',
        profilePictureKey: null,
        employeeId: 'EMP-012',
        salary: 95000.0,
        joiningDate: '2015-04-18',
        phoneNumber: '9876543222',
        status: EMPLOYEE_STATUS.OLD_EMPLOYEE,
        role: USER_ROLE.EMPLOYEE,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Alexander Clark',
        email: 'alexander.clark@gmail.com',
        password: hashedPassword,
        designation: DESIGNATION.LEAD_DEVELOPER,
        department: DEPARTMENT.ENGINEERING,
        dateOfBirth: '1988-12-04',
        profilePictureKey: null,
        employeeId: 'EMP-013',
        salary: 120000.0,
        joiningDate: '2016-02-28',
        phoneNumber: '9876543223',
        status: EMPLOYEE_STATUS.OLD_EMPLOYEE,
        role: USER_ROLE.EMPLOYEE,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Charlotte Lewis',
        email: 'charlotte.lewis@gmail.com',
        password: hashedPassword,
        designation: DESIGNATION.GRAPHIC_DESIGNER,
        department: DEPARTMENT.DESIGN,
        dateOfBirth: '1993-10-07',
        profilePictureKey: null,
        employeeId: 'EMP-014',
        salary: 70000.0,
        joiningDate: '2020-05-20',
        phoneNumber: '9876543224',
        status: EMPLOYEE_STATUS.CURRENT_EMPLOYEE,
        role: USER_ROLE.EMPLOYEE,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Daniel Walker',
        email: 'daniel.walker@gmail.com',
        password: hashedPassword,
        designation: DESIGNATION.BUSINESS_ANALYST,
        department: DEPARTMENT.BUSINESS,
        dateOfBirth: '1989-03-29',
        profilePictureKey: null,
        employeeId: 'EMP-015',
        salary: 88000.0,
        joiningDate: '2019-12-01',
        phoneNumber: '9876543225',
        status: EMPLOYEE_STATUS.CURRENT_EMPLOYEE,
        role: USER_ROLE.EMPLOYEE,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('users', {
      role: USER_ROLE.EMPLOYEE,
    });
  },
};
